name: 'Convert To Draft'
description: 'Convert open pull request to draft with no recent activity'
author: 'Ravi Raipuria'
inputs:
  repo-token:
    required: true
    description: 'Token for the repository. Can be passed in using `{{ secrets.GITHUB_TOKEN }}`.'
  days-before-convert-draft:
    description: 'The number of days to wait before converting a open pull request to draft.'
    required: true
  draft-pr-msg:
    description: 'Comment on draft pr'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: "git-pull-request"
  color: "black"